-- H2-compatible schema for integration tests
-- Replaces Hibernate DDL auto-generation to work around bigint[] incompatibility

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    category VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    venue VARCHAR(200) NOT NULL,
    event_date TIMESTAMP(6) NOT NULL,
    total_capacity INTEGER NOT NULL,
    available_seats INTEGER NOT NULL,
    base_price NUMERIC(10,2) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT','PUBLISHED','CANCELLED','COMPLETED')),
    organizer_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT
);

CREATE TABLE IF NOT EXISTS seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    section VARCHAR(50) NOT NULL,
    row_letter VARCHAR(10) NOT NULL,
    seat_number INTEGER NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('AVAILABLE','HELD','BOOKED')),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    version BIGINT,
    CONSTRAINT fk_seat_event FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS pricing_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    description VARCHAR(500),
    max_quantity INTEGER,
    available_quantity INTEGER,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_pricing_event FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(100) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    seat_ids BIGINT ARRAY NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('CONFIRMED','CANCELLED','REFUNDED')),
    payment_id VARCHAR(100),
    hold_token VARCHAR(100),
    created_at TIMESTAMP(6) NOT NULL,
    confirmed_at TIMESTAMP(6),
    cancelled_at TIMESTAMP(6),
    CONSTRAINT fk_booking_event FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS seat_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_token VARCHAR(100) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    seat_ids BIGINT ARRAY NOT NULL,
    seat_count INTEGER NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE','EXPIRED','CONFIRMED','CANCELLED')),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_hold_event FOREIGN KEY (event_id) REFERENCES events(id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_event_city_date ON events(city, event_date);
CREATE INDEX IF NOT EXISTS idx_event_category ON events(category);
CREATE INDEX IF NOT EXISTS idx_event_status ON events(status);
CREATE INDEX IF NOT EXISTS idx_seat_event_section ON seats(event_id, section);
CREATE INDEX IF NOT EXISTS idx_seat_status ON seats(status);
CREATE INDEX IF NOT EXISTS idx_seat_row_number ON seats(row_letter, seat_number);
CREATE INDEX IF NOT EXISTS idx_booking_customer ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS idx_booking_event ON bookings(event_id);
CREATE INDEX IF NOT EXISTS idx_booking_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_booking_date ON bookings(created_at);
CREATE INDEX IF NOT EXISTS idx_hold_customer ON seat_holds(customer_id);
CREATE INDEX IF NOT EXISTS idx_hold_expiry ON seat_holds(expires_at);
CREATE INDEX IF NOT EXISTS idx_hold_status ON seat_holds(status);
CREATE INDEX IF NOT EXISTS idx_pricing_event ON pricing_tiers(event_id);
